# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ddl5V6RKMDv14knzbeDgbZkK5BIiXNqR
"""

from google.colab import files
uploaded = files.upload()

!pip install pandas streamlit plotly

import pandas as pd

providers = pd.read_csv("providers_data.csv")
receivers = pd.read_csv("receivers_data.csv")
food = pd.read_csv("food_listings_data.csv")
claims = pd.read_csv("claims_data.csv")

providers.drop_duplicates(inplace=True)
receivers.drop_duplicates(inplace=True)
food.drop_duplicates(inplace=True)
claims.drop_duplicates(inplace=True)

import sqlite3

conn = sqlite3.connect("food_wastage.db")

providers.to_sql("providers", conn, if_exists="replace", index=False)
receivers.to_sql("receivers", conn, if_exists="replace", index=False)
food.to_sql("food_listings", conn, if_exists="replace", index=False)
claims.to_sql("claims", conn, if_exists="replace", index=False)

query = """
SELECT City,
COUNT(*) AS Total_Providers
FROM providers
GROUP BY City
"""

pd.read_sql(query, conn)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# import pandas as pd
# 
# st.title("Local Food Wastage Management System")
# 
# providers = pd.read_csv("providers_data.csv")
# 
# st.subheader("Providers Data")
# 
# st.dataframe(providers)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile requirements.txt
# streamlit
# pandas
# plotly
# numpy
# matplotlib